// Generated by CoffeeScript 1.12.7
(function() {
  $.ajaxSetup({
    cache: false
  });

  $.get('html/menu.html', function(html) {
    html = $(html);
    if ($(document).find("title").text() === "Etudes à l'étranger") {
      html.find('#carteMenu').addClass('active');
    } else {
      html.find('#infosMenu').addClass('active');
    }
    return $('nav').html(html);
  });

}).call(this);

//# sourceMappingURL=main.js.map
